name: Create Release on Version Bump

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases and tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Check if release for version already exists
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: v${{ steps.get_version.outputs.version }}
        run: |
          if gh release view "$TAG_NAME" > /dev/null 2>&1; then
            echo "Release for tag $TAG_NAME already exists. Skipping."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Release for tag $TAG_NAME does not exist. Proceeding."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: Automated release for version ${{ steps.get_version.outputs.version }}.
          draft: false
          prerelease: false
